force-app/main/default/objects/Campaign_Type_Member_Status__mdt/Campaign_Type_Member_Status__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type defines Protected campaign member status values. Campaigns with specific Type values will be given specific campaign member status values, and if those values are changed they will be reinstated</description>
    <label>Campaign Type Member Status</label>
    <pluralLabel>Campaign Type Member Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/Campaign_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Status__c</fullName>
    <label>Protected Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>The Campaign Type (not record type) for this Protected Status</description>
    <inlineHelpText>This is the actual value for the Campaign&apos;s Type field.</inlineHelpText>
    <label>Campaign Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/HasResponded__c.field-meta.xml
<CustomField>
    <fullName>HasResponded__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this if this Status should be marked as Responded</inlineHelpText>
    <label>Responded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tests/CampaignMemberRepositoryMocks.cls
/**
 * @description Mock classes for responses to be used across multiple Apex tests
 *
 * @author      Sercante LLC
 * @since       2022
 * @group       CampaignMemberStatusTests
 */
@isTest
public without sharing class CampaignMemberRepositoryMocks {
	/**
	 * Mock class for Campaign Type Member Status values for Webinar Campaign Type
	 */
	public class WebinarMock extends CampaignMemberRepository {
		public override Map<String, List<Campaign_Type_Member_Status__mdt>> getGroupedProtectedStatuses() {
			//System.debug('overriding actually getting MDTs from Salesforce, using hard coded Webinar MDTs');
			Map<String, List<Campaign_Type_Member_Status__mdt>> response = new Map<String, List<Campaign_Type_Member_Status__mdt>>();
			List<Campaign_Type_Member_Status__mdt> values = new List<Campaign_Type_Member_Status__mdt>();
			Campaign_Type_Member_Status__mdt registered = new Campaign_Type_Member_Status__mdt();
			registered.DeveloperName = 'Webinar_Registered';
			registered.Label = 'Webinar-Registered';
			registered.Campaign_Type__c = 'Webinar';
			registered.Campaign_Member_Status__c = '1Registered';
			registered.IsDefault__c = true;
			registered.HasResponded__c = false;
			values.add(registered);

			Campaign_Type_Member_Status__mdt attended = new Campaign_Type_Member_Status__mdt();
			attended.DeveloperName = 'Webinar_Attended';
			attended.Label = 'Webinar-Attended';
			attended.Campaign_Type__c = 'Webinar';
			attended.Campaign_Member_Status__c = '2Attended';
			attended.IsDefault__c = false;
			attended.HasResponded__c = true;
			values.add(attended);

			Campaign_Type_Member_Status__mdt watchedOnDemand = new Campaign_Type_Member_Status__mdt();
			watchedOnDemand.DeveloperName = 'Webinar_WatchedOnDemand';
			watchedOnDemand.Label = 'Webinar-WatchedOnDemand';
			watchedOnDemand.Campaign_Type__c = 'Webinar';
			watchedOnDemand.Campaign_Member_Status__c = '3Watched On Demand';
			watchedOnDemand.IsDefault__c = false;
			watchedOnDemand.HasResponded__c = true;
			values.add(watchedOnDemand);

			Campaign_Type_Member_Status__mdt didNotAttend = new Campaign_Type_Member_Status__mdt();
			didNotAttend.DeveloperName = 'Webinar_DidNotAttend';
			didNotAttend.Label = 'Webinar-DidNotAttend';
			didNotAttend.Campaign_Type__c = 'Webinar';
			didNotAttend.Campaign_Member_Status__c = '4Did Not Attend';
			didNotAttend.IsDefault__c = false;
			didNotAttend.HasResponded__c = false;
			values.add(didNotAttend);

			response.put('Webinar', values);
			return response;
		}
	}

	/**
	 * Mock class for Advertisement Campaign Type Member Status Value (only one status)
	 */
	public class AdvertisementMock extends CampaignMemberRepository {
		public override Map<String, List<Campaign_Type_Member_Status__mdt>> getGroupedProtectedStatuses() {
			//System.debug('overriding actually getting MDTs from Salesforce, using hard coded Advertisement MDTs');
			Map<String, List<Campaign_Type_Member_Status__mdt>> response = new Map<String, List<Campaign_Type_Member_Status__mdt>>();
			List<Campaign_Type_Member_Status__mdt> values = new List<Campaign_Type_Member_Status__mdt>();
			Campaign_Type_Member_Status__mdt onlyStatus = new Campaign_Type_Member_Status__mdt();
			onlyStatus.DeveloperName = 'Advertisement_Responded';
			onlyStatus.Label = 'Advertisement-Responded';
			onlyStatus.Campaign_Type__c = 'Advertisement';
			onlyStatus.Campaign_Member_Status__c = 'Responded';
			onlyStatus.IsDefault__c = true;
			onlyStatus.HasResponded__c = true;
			values.add(onlyStatus);

			response.put('Advertisement', values);
			return response;
		}
	}
}