force-app/main/default/objects/Campaign_Type_Member_Status__mdt/Campaign_Type_Member_Status__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type defines Protected campaign member status values. Campaigns with specific Type values will be given specific campaign member status values, and if those values are changed they will be reinstated</description>
    <label>Campaign Type Member Status</label>
    <pluralLabel>Campaign Type Member Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/Campaign_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Status__c</fullName>
    <label>Protected Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>The Campaign Type (not record type) for this Protected Status</description>
    <inlineHelpText>This is the actual value for the Campaign&apos;s Type field.</inlineHelpText>
    <label>Campaign Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/HasResponded__c.field-meta.xml
<CustomField>
    <fullName>HasResponded__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this if this Status should be marked as Responded</inlineHelpText>
    <label>Responded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tests/CampaignMemberServiceTest.cls
/**
 * @description Test class
 *
 * @author      Sercante LLC
 * @since       2022
 * @group       CampaignMemberStatusTests
 */
@SuppressWarnings('PMD.ApexUnitTestShouldNotUseSeeAllDataTrue')
@isTest
private class CampaignMemberServiceTest {
	@isTest(seeAllData=true)
	static void shouldEnforceProtectedStatusesForCampaign() {
		//arrange
		Test.enableChangeDataCapture();
		CampaignMemberService sut = CampaignMemberService.getInstance();
		sut.repo = new WebinarMock();

		Campaign camp = new Campaign(Name = 'MyTest', Type = 'Webinar', IsActive = true);
		insert camp;
		Test.getEventBus().deliver(); //clear the bus so that we later get Update events

		//act
		Test.startTest();
		//System.debug('start of test');

		//here we mess up our data
		delete [SELECT Id FROM CampaignMemberStatus WHERE Label = '3Watched On Demand'];
		CampaignMemberStatus registered = [SELECT Id FROM CampaignMemberStatus WHERE Label = '1Registered'];
		registered.HasResponded = true;
		update registered;
		System.Assert.isTrue(sut.getCampaignsNeedingToBeFixed().contains(camp.Id));
		Test.stopTest();

		//assert
		List<CampaignMemberStatus> results = [SELECT Id, Label, IsDefault, HasResponded FROM CampaignMemberStatus WHERE CampaignId = :camp.Id ORDER BY Label];
		Assert.areEqual('1Registered', results.get(0).Label);
		Assert.areEqual(false, results.get(0).HasResponded);
		Assert.areEqual('2Attended', results.get(1).Label);
		Assert.areEqual('3Watched On Demand', results.get(2).Label);
		Assert.areEqual('4Did Not Attend', results.get(3).Label);
	}

	private class WebinarMock extends CampaignMemberRepository {
		public override Map<String, List<Campaign_Type_Member_Status__mdt>> getGroupedProtectedStatuses() {
			//System.debug('overriding actually getting MDTs from Salesforce, using hard coded Webinar MDTs');
			Map<String, List<Campaign_Type_Member_Status__mdt>> response = new Map<String, List<Campaign_Type_Member_Status__mdt>>();
			List<Campaign_Type_Member_Status__mdt> values = new List<Campaign_Type_Member_Status__mdt>();
			Campaign_Type_Member_Status__mdt registered = new Campaign_Type_Member_Status__mdt();
			registered.DeveloperName = 'Webinar_Registered';
			registered.Label = 'Webinar-Registered';
			registered.Campaign_Type__c = 'Webinar';
			registered.Campaign_Member_Status__c = '1Registered';
			registered.IsDefault__c = true;
			registered.HasResponded__c = false;
			values.add(registered);

			Campaign_Type_Member_Status__mdt attended = new Campaign_Type_Member_Status__mdt();
			attended.DeveloperName = 'Webinar_Attended';
			attended.Label = 'Webinar-Attended';
			attended.Campaign_Type__c = 'Webinar';
			attended.Campaign_Member_Status__c = '2Attended';
			attended.IsDefault__c = false;
			attended.HasResponded__c = true;
			values.add(attended);

			Campaign_Type_Member_Status__mdt watchedOnDemand = new Campaign_Type_Member_Status__mdt();
			watchedOnDemand.DeveloperName = 'Webinar_WatchedOnDemand';
			watchedOnDemand.Label = 'Webinar-WatchedOnDemand';
			watchedOnDemand.Campaign_Type__c = 'Webinar';
			watchedOnDemand.Campaign_Member_Status__c = '3Watched On Demand';
			watchedOnDemand.IsDefault__c = false;
			watchedOnDemand.HasResponded__c = true;
			values.add(watchedOnDemand);

			Campaign_Type_Member_Status__mdt didNotAttend = new Campaign_Type_Member_Status__mdt();
			didNotAttend.DeveloperName = 'Webinar_DidNotAttend';
			didNotAttend.Label = 'Webinar-DidNotAttend';
			didNotAttend.Campaign_Type__c = 'Webinar';
			didNotAttend.Campaign_Member_Status__c = '4Did Not Attend';
			didNotAttend.IsDefault__c = false;
			didNotAttend.HasResponded__c = false;
			values.add(didNotAttend);

			response.put('Webinar', values);
			return response;
		}
	}
}