force-app/main/default/objects/Campaign_Type_Member_Status__mdt/Campaign_Type_Member_Status__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type defines Protected campaign member status values. Campaigns with specific Type values will be given specific campaign member status values, and if those values are changed they will be reinstated</description>
    <label>Campaign Type Member Status</label>
    <pluralLabel>Campaign Type Member Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/Campaign_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Status__c</fullName>
    <label>Protected Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>The Campaign Type (not record type) for this Protected Status</description>
    <inlineHelpText>This is the actual value for the Campaign&apos;s Type field.</inlineHelpText>
    <label>Campaign Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/HasResponded__c.field-meta.xml
<CustomField>
    <fullName>HasResponded__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this if this Status should be marked as Responded</inlineHelpText>
    <label>Responded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign_Type_Member_Status__mdt/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CampaignMemberRepository.cls
/**
 * @description Utility class to return statuses by Campaign Type
 *
 * @author      Sercante LLC
 * @since       2022
 * @group       CampaignMemberStatus
 */
public without sharing virtual class CampaignMemberRepository {
	/**
	 * @description Return `Campaign Type Member Status` CMDT records by Campaign Type
	 *
	 * @return      `Map<String, List<Campaign_Type_Member_Status__mdt>>`
	 */
	public virtual Map<String, List<Campaign_Type_Member_Status__mdt>> getGroupedProtectedStatuses() {
		List<Campaign_Type_Member_Status__mdt> protectedStatuses = [
			SELECT Label, Campaign_Type__c, Campaign_Member_Status__c, IsDefault__c, HasResponded__c
			FROM Campaign_Type_Member_Status__mdt
			ORDER BY Campaign_Type__c, IsDefault__c DESC, HasResponded__c DESC
		];

		Map<String, List<Campaign_Type_Member_Status__mdt>> groupedProtectedStatuses = new Map<String, List<Campaign_Type_Member_Status__mdt>>();
		for (Campaign_Type_Member_Status__mdt status : protectedStatuses) {
			if (!groupedProtectedStatuses.containsKey(status.Campaign_Type__c)) {
				groupedProtectedStatuses.put(status.Campaign_Type__c, new List<Campaign_Type_Member_Status__mdt>());
			}
			groupedProtectedStatuses.get(status.Campaign_Type__c).add(status);
		}
		return groupedProtectedStatuses;
	}
}